// <auto-generated />
using System;
using BaezStone.MagicVilla.Api.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaezStone.MagicVilla.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407164500_TestQuitarAtributoIdentity")]
    partial class TestQuitarAtributoIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaezStone.MagicVilla.Api.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            FechaActualizacion = new DateTime(2026, 4, 7, 11, 44, 59, 958, DateTimeKind.Local).AddTicks(8275),
                            FechaCreacion = new DateTime(2026, 4, 7, 11, 44, 59, 958, DateTimeKind.Local).AddTicks(8258),
                            ImagenURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            MetrosCuadrados = 550,
                            Nombre = "Villa Real",
                            Ocupantes = 4,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            FechaActualizacion = new DateTime(2026, 4, 7, 11, 44, 59, 958, DateTimeKind.Local).AddTicks(8278),
                            FechaCreacion = new DateTime(2026, 4, 7, 11, 44, 59, 958, DateTimeKind.Local).AddTicks(8278),
                            ImagenURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg",
                            MetrosCuadrados = 550,
                            Nombre = "Premium Pool Villa",
                            Ocupantes = 4,
                            Tarifa = 300.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
