@baseUrl = https://localhost:7093
@contentType = application/json
@patchContentType = application/json-patch+json

GET {{baseUrl}}/api/Villa

###

GET {{baseUrl}}/api/Villa/1

###

POST {{baseUrl}}/api/Villa
Content-Type: {{contentType}}

{
  "nombre": "Villa El Salvador",
  "detalle": "Detalle de la Villa Fátima",
  "tarifa": 200.0,
  "ocupantes": 4,
  "metroscuadrados": 500,
  "imagenurl": "https://example.com/villa-fatima.jpg",
  "amenidad": "Piscina privada"
}

###
@id = 3
DELETE {{baseUrl}}/api/Villa/{{id}}
Accept: {{contentType}}

###

PATCH {{baseUrl}}/api/Villa/1
Content-Type: {{patchContentType}}

[
  { "op": "replace", "path": "/nombre", "value": "Nueva Villa Fátima" }
]

