@baseUrl = https://localhost:7093
@contentType = application/json
@patchContentType = application/json-patch+json

GET {{baseUrl}}/api/Villa

###

@idx = 1001
GET {{baseUrl}}/api/Villa/{{idx}}

###

POST {{baseUrl}}/api/Villa
Content-Type: {{contentType}}

{
  "nombre": "Villa El Porvenir",
  "detalle": "Detalle de la Villa Maria",
  "tarifa": 200.0,
  "ocupantes": 4,
  "metroscuadrados": 500,
  "imagenurl": "https://example.com/villa-fatima.jpg",
  "amenidad": "Piscina privada"
}

###

@ida = 1001
PUT {{baseUrl}}/api/Villa/{{ida}}
Content-Type: {{contentType}}

{
  "id": {{ida}}, 
  "nombre": "Villa El Porvenir",
  "detalle": "Detalle de la Villa Maria",
  "ocupantes": 4,
  "metrosCuadrados": 500,
  "tarifa": 200.0,
  "imagenUrl": null,
  "amenidad": "Piscina privada"
}

###
@idy = 1001
DELETE {{baseUrl}}/api/Villa/{{idy}}
Accept: {{contentType}}

###
@idz = 1002
PATCH {{baseUrl}}/api/Villa/{{idz}}
Content-Type: {{patchContentType}}

[  
  { "op": "replace", "path": "/imagenUrl", "value": "https://example.com/villa-fatima-300.jpg" }
]

