@baseUrl = https://localhost:7093
@contentType = application/json
@patchContentType = application/json-patch+json

GET {{baseUrl}}/api/Villa

###

@idx = 5
GET {{baseUrl}}/api/Villa/{{idx}}

###

POST {{baseUrl}}/api/Villa
Content-Type: {{contentType}}

{
  "nombre": "Villa Test",
  "detalle": "Detalle de la Villa Test",
  "tarifa": 200.0,
  "ocupantes": 4,
  "metroscuadrados": 500,
  "imagenurl": "https://example.com/villa-fatima.jpg",
  "amenidad": "Piscina privada"
}

###
@idy = 3
DELETE {{baseUrl}}/api/Villa/{{idy}}
Accept: {{contentType}}

###
@idz = 5
PATCH {{baseUrl}}/api/Villa/{{idz}}
Content-Type: {{patchContentType}}

[
  { "op": "replace", "path": "/detalle", "value": "Otros Detalle de la Nueva Villa Test" }
]

